# Global Risk Management Configuration for JuliaOS Agents/DEXes

[max_trade_size]
# Maximum trade size per DEX (in USD)
uniswap = 1000.0
sushiswap = 1000.0
pancakeswap = 1000.0
quickswap = 1000.0
traderjoe = 1000.0
raydium = 1000.0

[stop_loss]
# Stop-loss percentage per trade (e.g., 5 means 5% loss triggers stop)
enabled = true
percent = 5.0

[take_profit]
# Take-profit percentage per trade (e.g., 10 means 10% gain triggers take-profit)
enabled = true
percent = 10.0

[exposure_limits]
# Maximum exposure per asset (in USD)
WETH = 5000.0
USDC = 5000.0
BTC = 5000.0

[daily_loss_limits]
# Maximum daily loss allowed (in USD)
enabled = true
max_loss_usd = 2000.0

[custom_rules]
# Add any custom risk rules here as needed
# Example: minimum account balance, cooldown period, etc.
min_account_balance_usd = 100.0
trade_cooldown_seconds = 60
