# render.yaml - Ghost Wallet Hunter Services Configuration
# Configuração para deploy automático no Render com MONOREPO

services:
  # 🐍 SERVIÇO 1: Python Backend (EXISTENTE)
  - type: web
    name: ghost-backend
    runtime: python
    rootDir: backend
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 30
    plan: starter  # $7/mês
    region: oregon
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: JULIAOS_BASE_URL
        value: https://juliaos-core.onrender.com
      - key: OPENAI_API_KEY
        sync: false
      - key: GROK_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false

  # 💎 SERVIÇO 2: JuliaOS Backend (NOVO)
  - type: web
    name: ghost-julia
    runtime: docker
    rootDir: juliaos-core/backend
    dockerfilePath: ./Dockerfile.render
    plan: starter  # $7/mês
    region: oregon
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8052
      # Database connection (será criado automaticamente)
      - key: DB_HOST
        fromDatabase:
          name: ghost-julia-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: ghost-julia-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: ghost-julia-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: ghost-julia-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ghost-julia-db
          property: password
      # AI API Keys (mesmas do backend Python)
      - key: OPENAI_API_KEY
        sync: false
      - key: GROK_API_KEY
        sync: false

# 💾 DATABASE: PostgreSQL para JuliaOS
databases:
  - name: ghost-julia-db
    databaseName: juliaos
    user: juliaos_user
    plan: starter  # $7/mês
    region: oregon
