# render.yaml - Ghost Wallet Hunter Backend Python
# Deploy configuration for Python FastAPI service

services:
  - type: web
    name: ghost-backend
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 30
    plan: starter
    region: oregon
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: JULIAOS_BASE_URL
        value: https://ghost-julia.onrender.com
      - key: OPENAI_API_KEY
        sync: false
      - key: GROK_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
