# coding: utf-8

"""
    JuliaOS API

    API for JuliaOS backend server

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, Optional
from pydantic import BaseModel, Field, StrictStr, validator

class AgentSummary(BaseModel):
    """
    AgentSummary
    """
    id: StrictStr = Field(...)
    name: StrictStr = Field(default=..., description="Human-readable name of the agent")
    description: StrictStr = Field(default=..., description="Brief summary of what the agent does")
    state: StrictStr = Field(default=..., description="The current state of the agent")
    trigger_type: StrictStr = Field(default=..., description="Specifies how the agent is activated")
    input_schema: Optional[Dict[str, Any]] = Field(default=None, description="JSON-Schema describing the structure the agent expects as input when its `run` endpoint is invoked. Omitted when the agent declares no input type. ")
    __properties = ["id", "name", "description", "state", "trigger_type", "input_schema"]

    @validator('state')
    def state_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('CREATED', 'RUNNING', 'PAUSED', 'STOPPED'):
            raise ValueError("must be one of enum values ('CREATED', 'RUNNING', 'PAUSED', 'STOPPED')")
        return value

    @validator('trigger_type')
    def trigger_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('PERIODIC', 'WEBHOOK'):
            raise ValueError("must be one of enum values ('PERIODIC', 'WEBHOOK')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AgentSummary:
        """Create an instance of AgentSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AgentSummary:
        """Create an instance of AgentSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AgentSummary.parse_obj(obj)

        _obj = AgentSummary.parse_obj({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "state": obj.get("state"),
            "trigger_type": obj.get("trigger_type"),
            "input_schema": obj.get("input_schema")
        })
        return _obj


