# A2A Server Deploy - MINIMAL VERSION
services:
  - type: web
    name: ghost-a2a-server
    runtime: docker
    dockerfilePath: docker/Dockerfile.minimal
    plan: starter
    region: oregon
    rootDir: juliaos/a2a
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: JULIA_HOST
        value: https://ghost-wallet-hunter-juliaos.onrender.com
      - key: A2A_PORT
        value: "10000"
      - key: PORT
        value: "10000"
    healthCheckPath: /health
    autoDeploy: true
    branch: main
