name = "JuliaOS"
uuid = "12345678-1234-5678-1234-567812345678"
authors = ["JuliaOS Contributors <contributors@juliaos.org>"]
version = "0.1.0"

[deps]
# Core essentials only
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

# Only if needed for specific features
# Remove heavy packages: Flux, BenchmarkTools, Cascadia, Gumbo, LibPQ
# These consume ~300MB+ in memory
