# JuliaOS Deploy - MINIMAL VERSION
services:
  - type: web
    name: ghost-wallet-hunter-juliaos
    runtime: docker
    plan: starter
    dockerfilePath: ./docker/Dockerfile
    rootDir: juliaos
    envVars:
      - key: JULIA_VERSION
        value: "1.11.6"
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: "8052"
      - key: A2A_PORT
        value: "9100"
      - key: JULIA_NUM_THREADS
        value: "1"
      - key: JULIA_NUM_GC_THREADS
        value: "1"
      - key: JULIA_DEPOT_PATH
        value: "/tmp/.julia"
      - key: JULIA_MAX_NUM_PRECOMPILE_FILES
        value: "20"
    healthCheckPath: /health
    autoDeploy: true
    branch: main
