# JuliaOS Deploy - MINIMAL VERSION
services:
  - type: web
    name: ghost-wallet-hunter-juliaos
    runtime: docker
    plan: starter
    dockerfilePath: ./docker/Dockerfile.minimal
    rootDir: juliaos
    envVars:
      - key: JULIA_VERSION
        value: "1.11.6"
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: "8052"
      - key: A2A_PORT
        value: "9100"
    healthCheckPath: /health
    autoDeploy: true
    branch: main
