# JuliaOS Deploy - MINIMAL VERSION
services:
  - type: web
    name: ghost-wallet-hunter-juliaos
    runtime: docker
    plan: standard  # 🚀 2GB RAM - NO MORE LIMITATIONS!
    dockerfilePath: ./docker/Dockerfile
    rootDir: juliaos
    envVars:
      - key: JULIA_VERSION
        value: "1.11.6"
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: "8052"
      - key: A2A_PORT
        value: "9100"
      - key: JULIA_NUM_THREADS
        value: "4"
      - key: JULIA_NUM_GC_THREADS
        value: "2"
      - key: JULIA_DEPOT_PATH
        value: "/app/.julia"
      - key: JULIA_PROJECT
        value: "/app"
    healthCheckPath: /health
    autoDeploy: true
    branch: main
